[wip] Add more api tests
DevSkillsHQ/transaction-management-backend-level-1 pull request #16
Opened 2023-02-19 20:34 UTC by paliwodar

2023-02-20 22:56 UTC, fenske requested changes
Thanks for the PR!

The best way to validate test suite changes would be running them against a reference implementation.

In this case, we have https://infra.devskills.app/api/transaction-management that's referred from inside [the OpenAPI spec](https://infra.devskills.app/transaction-management/api/3.1.0) (here's [the implementation](https://github.com/devskills-robot/infra/tree/master/pages/api/transaction-management) itself).

I ran both on the pipeline and Gitpod ([link](https://gitpod.io/#https://github.com/DevSkillsHQ/transaction-management-backend-level-1)) and it failed on the new test case. See Cypress images below:

![Transaction Management Backend - Level 1 -- Can handle invalid requests (failed)](https://user-images.githubusercontent.com/1162212/220209610-50142660-2c0f-474a-9a98-254fab450b9a.png)

![Transaction Management Backend - Level 1 -- Can read all created transactions (failed)](https://user-images.githubusercontent.com/1162212/220209604-8679d6d3-8c2b-4109-9cc1-5a227705c438.png)

Did it work for you when you tested it?

2023-02-20 22:56 UTC, fenske commented on cypress/integration/backend.spec.js
> +  t('Can read all created transactions', () => {
```suggestion
  it('Can read all created transactions', () => {
```

2023-02-25 21:23 UTC, paliwodar commented on cypress/integration/backend.spec.js
> +  t('Can read all created transactions', () => {
Fixed!

2023-02-27 14:46 UTC, paliwodar commented
> I tested it on a separate branch and all tests pass now. I saw you mentioned it in Notion that you'd think about adding more tests. Do you want to do it as part of this PR or separate?

Fine to merge this one for me. I'd add more if any in a separate one.

2023-02-28 07:49 UTC, merged

2023-04-01 17:36 UTC, paliwodar commented
> I saw you mentioned it in Notion that you'd think about adding more tests. Do you want to do it as part of this PR or separate?

IMO we are good with the tests. I will raise this in Notion.